name: "Test Files Merger"
description: "Merges repositoryname.json and orchestrator.json from vickjoeobi/testFiles"
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/src/install-dependencies.js
      shell: node
    - run: ${{ github.action_path }}/src/main.js
      shell: node
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
