name: Test Files Merger

on:
  push:
    branches:
      - main

jobs:
  merge_test_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge test files
        uses: vickjoeobi/test-files-merger@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
